version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: portfolio
            POSTGRES_PASSWORD: portfolio123
        ports:
          - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
